project:
  type: website
  output-dir: docs

website:
  title: "Heather Terada"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - R-work.qmd
  sidebar:
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/heatherterada/
      - icon: linkedin

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    code-fold: true

