project:
  type: website
  output-dir: docs

website:
  title: "HT in PDX"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - R-work.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true



