project:
  type: website
  output-dir: docs

website:
  title: "Heather Terada"
  navbar:
    left:
      - icon: linkedin
        href: https://www.linkedin.com/in/heatherterada/
      - icon: github
        href: https://github.com/txhorse89/
      - href: index.qmd
        text: Home
      - about.qmd
      - R-work.qmd


format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    code-fold: true

