---
title: "About Me"
---

Heather Terada is passionate about cross-cultural communications and bridging the relationship between the US and Japan. Gaining an interest in Japanese culture and language during her undergraduate degree in Asian Studies, Heather decided to earn her Masters in International Relations at Waseda University in Japan where she fell in love with the culture and decided to begin her career full time. 

Over the last decade, Heather has worked at companies like MetLife and Rakuten building skills in intercultural communication and data analysis. Currently, she is the Data Analytics Manager at Sony in the Risk and Control department. 

Heather has returned to the US to level up her skills by pursuing her Masters of Science in Data Science at her alma mater, Willamette University, and hopes to share her work experiences with people who are interested in pursuing a corporate career in Japan, especially women in the STEM fields. She would love to connect on LinkedIn or meet to grab a coffee while she’s in Portland.